version: '2'
services:
  zookeeper:
    container_name: heartbeat_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - deploy
  kafka:
    container_name: heartbeat_kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://43.202.219.160:9092
      KAFKA_CREATE_TOPICS: "heartbeat-raw-topic:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
			KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deploy
networks:
  deploy:
    external: true
