# application-prod.yml
spring:
  kafka:
    producer:
      retries: 0
      buffer-memory: ${buffer-memory}
      request:
        timeout:
          ms: $P{ms}
      acks: 0
      bootstrap-servers: ${bootstrap-servers}

logging:
  level:
    com.gunpang.heartservice: INFO
