spring:
  application:
    name: heartbeat-consume
  kafka:
    bootstrap-servers: ${bootstrap-prod-server}
    streams:
      application-id: heartbeat-consume

logging:
  level:
    com.gunpang.heartservice: INFO